AllCops:
  TargetRubyVersion: 2.7

Lint/SuppressedException:
  Enabled: false

Lint/AssignmentInCondition:
  Exclude:
    - 'spec/**/*.rb'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - '*.gemspec'
Style/FormatString:
  Enabled: false
Style/Documentation:
  Enabled: false
# This is causing breaking changes:
Style/ExpandPathArguments:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*.rb'
Metrics/MethodLength:
  Enabled: false
